# Generated by Django 3.1 on 2020-08-15 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200815_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
