# Generated by Django 3.1 on 2020-08-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_bidders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bidders',
        ),
        migrations.AddField(
            model_name='listing',
            name='bidder',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.Listing'),
        ),
    ]
