# Generated by Django 3.1 on 2020-08-15 06:59

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200815_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='auctions/images'),
        ),
    ]
