# Generated by Django 3.1 on 2020-08-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
